### PR TITLE
Pass by reference

### PR DESCRIPTION
**Pull request by Shusei-E**
Pass by reference might be faster: https://www.learncpp.com/cpp-tutorial/73-passing-arguments-by-reference/

### CODE REVIEW

**Comment by sou412** [comment]
@kuriwaki

**Comment by Shusei-E** [comment]
Another idea to make it faster is to write the entire for loop in Rcpp.

There are two ways to do it:
1. Write `for (u 1:data$U)` loop in Rcpp (you will need RcppEigen)
2. Write `for(k in 1:user_K)` loop in Rcpp

Now it's already 1500x faster, it is not necessary, of course.

**Comment by kuriwaki** [comment]
Thanks! I’m new to pass by reference but sounds natural for this case. Will read up on it and merge.

**Comment by kuriwaki** [comment]
@Shusei-E just curious on your last point, why would we need RcppEigen in the i loop but not the k loop? Is it because I have a inner product inside the former? (https://github.com/kuriwaki/cat-mixture/blob/c74d4b13aa21d8aa6c4919a2de80e2d35497200f/03_define_EM-fun.R#L220)

And if I have a cpp function that loops over i (u), that necessarily means I will write the loop over k in cpp too (because the two are nested). Is that right?

**Comment by Shusei-E** [comment]
Yes, that is my thought (I didn't carefully check the dimension, but probably `.dot()` in Eigen computes it).

And yes, you can call an R function in Rcpp, but writing both loops would be easier.

I guess just creating `resp_u` in Rcpp can achieve a similar speed because matrix calculation is not expensive. You can return `NumericVector` object in Rcpp.

Maybe you can firstly set how fast the code should be and then replace parts that are slow in R.

**Comment by kuriwaki** [comment]
It looks like passing by reference vs. passing by value in this case does not make a noticeable difference in speed. Maybe this is because there is no updating of the arguments in this particular function and the inputs are only scalars  ..

**Comment by Shusei-E** [comment]
It could be the case that the cost of copying `int` and `double` is so low that there isn't a big difference. (In my project, I was originally passing an Eigen vector and it became 40% faster. Sorry for taking your time on this point.)

**Comment by kuriwaki** [comment]
Will try it when extending the functions such that they take the entire Y matrix as input. no no, it was very helpful!

**Pull request merged**
